# -*- coding: utf-8 -*-
"""Student Grade Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qPmK-N_7CfehlEjKT5Owm0SHMw9Uqrv
"""

import streamlit as st

st.set_page_config(page_title="Student Predictor", layout="wide")
st.title(" Student Predictor Chatbot")
