# -*- coding: utf-8 -*-
"""Student Grade Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qPmK-N_7CfehlEjKT5Owm0SHMw9Uqrv
"""

import streamlit as st
import re

st.set_page_config(page_title="Student Predictor", layout="wide")
st.title("Student Predictor Chatbot")

with st.sidebar:
    st.title("Student Predictor Chatbot")
    st.write("The Student Grade Predictor Chatbot is an intelligent conversational AI system that helps students predict their final grades and understand their academic performance. The chatbot combines rule-based conversation with grade calculation logic to provide personalized academic insights.")
    st.sidebar.divider()
    st.sidebar.header("Student Information")
    student_name = st.sidebar.text_input("Student Name")
    year_level = st.sidebar.selectbox(
        "Year Level",
        ["First year", "Second year", "Third year", "Fourth year"]
    )
    current_gpa = st.sidebar.number_input("Current GPA", 0.0, 4.0, 3.0)
    st.sidebar.progress(0.75, text="75% towards target grade")
    
    st.sidebar.header("Study Habits")
    study_hours = st.sidebar.number_input(
        "Study Hours per Week",
        min_value=0,
        max_value=168,
        value=10
    )
    attendance = st.sidebar.slider(
        "Attendance Rate (%)",
        min_value=0,
        max_value=100,
        value=80
    )
    
    st.sidebar.header("Other Factors")
    extracurriculars = st.sidebar.multiselect(
        "Extracurricular Activities",
        ["Sports", "Music", "Chess", "Drama", "Volunteer Work", "Table tennis", "Christian Union"]
    )
    previous_grade = st.sidebar.selectbox(
        "Previous Course Grade",
        ["A", "B", "C", "D", "F"]
    )
    
    st.sidebar.header("Exam Information")
    exam_date = st.sidebar.date_input("Exam Date")
    confidence = st.slider("Confidence level", 50, 100, 80)

if "history" not in st.session_state:
    st.session_state.history = []

if "scores" not in st.session_state:
    st.session_state.scores = {}

for msg in st.session_state.history:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

def detect_intent(user_input):
    input_lower = user_input.lower()
    if any(word in input_lower for word in ["hello", "hi", "hey"]):
        return "greeting"
    elif "predict" in input_lower and "grade" in input_lower:
        return "predict"
    elif any(word in input_lower for word in ["help", "how", "work"]):
        return "help"
    elif any(word in input_lower for word in ["bye", "exit", "quit"]):
        return "exit"
    elif re.search(r'\b(math|science|english|history):\s*\d+', input_lower):
        return "provide_scores"
    else:
        return "fallback"

def generate_response(intent, user_input):
    if intent == "greeting":
        return "Hello! I'm your Student Grade Predictor chatbot. I can help predict grades based on your scores. Just share them like 'math: 85' or ask for a prediction!"
    elif intent == "provide_scores":
        scores = {}
        matches = re.findall(r'(\w+):\s*(\d+)', user_input.lower())
        for subject, score in matches:
            scores[subject] = int(score)
        st.session_state.scores.update(scores)
        return f"Thanks! I've noted your scores: {scores}. Say 'predict my grade' to get a prediction."
    elif intent == "predict":
        if st.session_state.scores:
            total = sum(st.session_state.scores.values())
            avg = total / len(st.session_state.scores)
            if avg >= 90:
                grade = "A"
            elif avg >= 80:
                grade = "B"
            elif avg >= 70:
                grade = "C"
            elif avg >= 60:
                grade = "D"
            else:
                grade = "F"
            return f"Based on your scores (average: {avg:.1f}%), your predicted grade is {grade}. Keep up the great work!"
        else:
            return "I don't have any scores yet. Please provide some first, like 'math: 85'."
    elif intent == "help":
        return "I'm a simple chatbot that predicts grades from scores you provide. Examples: 'math: 85 science: 90' then 'predict my grade'. Type 'bye' to exit."
    elif intent == "exit":
        return "Goodbye! Thanks for chatting. Have a great day!"
    else:
        return "Sorry, I didn't understand that. Try saying 'hello', providing scores like 'math: 85', or asking for help!"

user_input = st.chat_input("Ask me anything on grade prediction:")

if user_input:
    st.session_state.history.append({"role": "user", "content": user_input})
    
    with st.chat_message("user"):
        st.write(user_input)
    
    intent = detect_intent(user_input)
    response = generate_response(intent, user_input)
    
    st.session_state.history.append({"role": "assistant", "content": response})
    
    with st.chat_message("assistant"):
        st.write(response)
    
    st.rerun()
